### ISSUE TITLE
ModuleNotFoundError: No module named 'openalea.maizetrack'

### ISSUE THREAD

**Issue by Illustratien** [openalea/phenotrack3d#6]
Hi,

When I try 
`(phenotrack) C:\Users\twang\phenotrack3d\examples>python tutorial_leaf_extension.py`
I got
`ModuleNotFoundError: No module named 'openalea.maizetrack'`
I can see `maizetrack.py` is in the folder of `src` in this repository but still failed to import.

Any clue?
Thanks.
Tien

**Comment by Illustratien** [comment]
Update:
I find out this could be due to the error in not able to run `python setup.py` for path setting.
I run
`(phenotrack) C:\Users\twang\phenotrack3d>python setup.py` 

I got
```
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```

**Comment by pradal** [comment]
Run

python setup.py install

or

python setup.py develop

Le 27/03/2023 à 22:20, Tien-Cheng a écrit :

**Comment by Illustratien** [comment]
Thanks @pradal.

Now after  installing setyp.py

Maybe alinea is also required to be install when create the conda environment?
```
Traceback (most recent call last):
  File "examples/tutorial_leaf_extension.py", line 8, in <module>
    from openalea.maizetrack.leaf_extension import leaf_extension
  File "c:\users\twang\appdata\local\r-miniconda\envs\phenotrack\lib\site-packages\openalea.maizetrack-0.1.3-py3.8.egg\openalea\maizetrack\leaf_extension.py", line 20, in <module>
    from openalea.maizetrack.utils import phm3d_to_px2d
  File "c:\users\twang\appdata\local\r-miniconda\envs\phenotrack\lib\site-packages\openalea.maizetrack-0.1.3-py3.8.egg\openalea\maizetrack\utils.py", line 6, in <module>
    from alinea.phenoarch.shooting_frame import get_shooting_frame
ModuleNotFoundError: No module named 'alinea'
```

**Comment by Illustratien** [comment]
I try with this command to install alinea
``(phenotrack) C:\Users\twang\phenotrack3d>conda install -c openalea alinea.astk
`` 
but failed.
```

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

**Comment by pradal** [comment]
No. This is an error. 
`alinea.phenoarch`is an internal package
